version: '3.8'

services:
  steam-price-bot:
#    build: .
    image: ghcr.io/driftywinds/steamrise
    container_name: steam-price-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      # Override data file path to use volume
      - DATA_FILE=/app/data/data.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
